# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
  # Just plain old shell command. You could use `make` as well.
  cmd = "go build -o ./tmp/main ."
  # Binary file yields from `cmd`.
  bin = "./tmp/main"
  # Customize binary.
  # for instance full_bin = "APP_ENV=dev APP_USER=air ./tmp/main"
  full_bin = ""
  # Watch these filename extensions.
  include_ext = ["go"]
  # Ignore these filename extensions or directories.
  exclude_dir = ["tmp", "logs", "public", "build", ".idea"]
  # Watch these directories if you specified.
  include_dir = []
  # Exclude files.
  exclude_file = []
  # Exclude specific regular expressions.
  exclude_regex = ["_test.go"]
  # Exclude unchanged files.
  exclude_unchanged = true
  # Follow symlink for directories
  follow_symlink = false
  # This log file places in your tmp_dir.
  log = "air.log"
  # It's not necessary to trigger build each time file changes if it's too frequent.
  delay = 1000 # ms
  # Stop running old binary when build errors occur.
  stop_on_error = true
  # Send Interrupt signal before killing process (windows does not support this feature)
  send_interrupt = false
  # Delay after sending Interrupt signal
  kill_delay = "0s" # ms

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
