// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/grpc/device/device.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mac           string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	ApiToken      string                 `protobuf:"bytes,4,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_grpc_device_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_device_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_device_device_proto_rawDescGZIP(), []int{0}
}

func (x *StatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *StatusRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *StatusRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	On            bool                   `protobuf:"varint,1,opt,name=on,proto3" json:"on,omitempty"`
	Temperature   int32                  `protobuf:"varint,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Mode          int32                  `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	FanSpeed      int32                  `protobuf:"varint,4,opt,name=fan_speed,json=fanSpeed,proto3" json:"fan_speed,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    int64                  `protobuf:"varint,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_grpc_device_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_device_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_device_device_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

func (x *StatusResponse) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *StatusResponse) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *StatusResponse) GetFanSpeed() int32 {
	if x != nil {
		return x.FanSpeed
	}
	return 0
}

func (x *StatusResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StatusResponse) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

type ValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mac           string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	ApiToken      string                 `protobuf:"bytes,4,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	On            bool                   `protobuf:"varint,5,opt,name=on,proto3" json:"on,omitempty"`
	Temperature   int32                  `protobuf:"varint,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Mode          int32                  `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`
	FanSpeed      int32                  `protobuf:"varint,8,opt,name=fan_speed,json=fanSpeed,proto3" json:"fan_speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuesRequest) Reset() {
	*x = ValuesRequest{}
	mi := &file_api_grpc_device_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesRequest) ProtoMessage() {}

func (x *ValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_device_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesRequest.ProtoReflect.Descriptor instead.
func (*ValuesRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_device_device_proto_rawDescGZIP(), []int{2}
}

func (x *ValuesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ValuesRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ValuesRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *ValuesRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *ValuesRequest) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

func (x *ValuesRequest) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ValuesRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ValuesRequest) GetFanSpeed() int32 {
	if x != nil {
		return x.FanSpeed
	}
	return 0
}

type ValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValuesResponse) Reset() {
	*x = ValuesResponse{}
	mi := &file_api_grpc_device_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValuesResponse) ProtoMessage() {}

func (x *ValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_device_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValuesResponse.ProtoReflect.Descriptor instead.
func (*ValuesResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_device_device_proto_rawDescGZIP(), []int{3}
}

func (x *ValuesResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ValuesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_grpc_device_device_proto protoreflect.FileDescriptor

const file_api_grpc_device_device_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/device/device.proto\x12\x06device\"b\n" +
	"\rStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x1b\n" +
	"\tapi_token\x18\x04 \x01(\tR\bapiToken\"\xb3\x01\n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02on\x18\x01 \x01(\bR\x02on\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x05R\vtemperature\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\x05R\x04mode\x12\x1b\n" +
	"\tfan_speed\x18\x04 \x01(\x05R\bfanSpeed\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\x06 \x01(\x03R\n" +
	"modifiedAt\"\xc5\x01\n" +
	"\rValuesRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x1b\n" +
	"\tapi_token\x18\x04 \x01(\tR\bapiToken\x12\x0e\n" +
	"\x02on\x18\x05 \x01(\bR\x02on\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x05R\vtemperature\x12\x12\n" +
	"\x04mode\x18\a \x01(\x05R\x04mode\x12\x1b\n" +
	"\tfan_speed\x18\b \x01(\x05R\bfanSpeed\"B\n" +
	"\x0eValuesResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x84\x01\n" +
	"\x06Device\x12<\n" +
	"\tGetStatus\x12\x15.device.StatusRequest\x1a\x16.device.StatusResponse\"\x00\x12<\n" +
	"\tSetValues\x12\x15.device.ValuesRequest\x1a\x16.device.ValuesResponse\"\x00B3Z1github.com/Ks89/air-conditioner/api-server/deviceb\x06proto3"

var (
	file_api_grpc_device_device_proto_rawDescOnce sync.Once
	file_api_grpc_device_device_proto_rawDescData []byte
)

func file_api_grpc_device_device_proto_rawDescGZIP() []byte {
	file_api_grpc_device_device_proto_rawDescOnce.Do(func() {
		file_api_grpc_device_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_device_device_proto_rawDesc), len(file_api_grpc_device_device_proto_rawDesc)))
	})
	return file_api_grpc_device_device_proto_rawDescData
}

var file_api_grpc_device_device_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_grpc_device_device_proto_goTypes = []any{
	(*StatusRequest)(nil),  // 0: device.StatusRequest
	(*StatusResponse)(nil), // 1: device.StatusResponse
	(*ValuesRequest)(nil),  // 2: device.ValuesRequest
	(*ValuesResponse)(nil), // 3: device.ValuesResponse
}
var file_api_grpc_device_device_proto_depIdxs = []int32{
	0, // 0: device.Device.GetStatus:input_type -> device.StatusRequest
	2, // 1: device.Device.SetValues:input_type -> device.ValuesRequest
	1, // 2: device.Device.GetStatus:output_type -> device.StatusResponse
	3, // 3: device.Device.SetValues:output_type -> device.ValuesResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_device_device_proto_init() }
func file_api_grpc_device_device_proto_init() {
	if File_api_grpc_device_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_device_device_proto_rawDesc), len(file_api_grpc_device_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_device_device_proto_goTypes,
		DependencyIndexes: file_api_grpc_device_device_proto_depIdxs,
		MessageInfos:      file_api_grpc_device_device_proto_msgTypes,
	}.Build()
	File_api_grpc_device_device_proto = out.File
	file_api_grpc_device_device_proto_goTypes = nil
	file_api_grpc_device_device_proto_depIdxs = nil
}
