// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: api/grpc/device/device.proto

package device

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FeatureUuid   string                 `protobuf:"bytes,2,opt,name=featureUuid,proto3" json:"featureUuid,omitempty"`
	FeatureName   string                 `protobuf:"bytes,3,opt,name=featureName,proto3" json:"featureName,omitempty"`
	Mac           string                 `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	ApiToken      string                 `protobuf:"bytes,5,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_api_grpc_device_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_device_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_device_device_proto_rawDescGZIP(), []int{0}
}

func (x *GetValueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetValueRequest) GetFeatureUuid() string {
	if x != nil {
		return x.FeatureUuid
	}
	return ""
}

func (x *GetValueRequest) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *GetValueRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *GetValueRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

type GetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeatureUuid   string                 `protobuf:"bytes,1,opt,name=featureUuid,proto3" json:"featureUuid,omitempty"`
	FeatureName   string                 `protobuf:"bytes,2,opt,name=featureName,proto3" json:"featureName,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Value         float32                `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    int64                  `protobuf:"varint,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_api_grpc_device_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_device_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_device_device_proto_rawDescGZIP(), []int{1}
}

func (x *GetValueResponse) GetFeatureUuid() string {
	if x != nil {
		return x.FeatureUuid
	}
	return ""
}

func (x *GetValueResponse) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *GetValueResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetValueResponse) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetValueResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetValueResponse) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

type SetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FeatureUuid   string                 `protobuf:"bytes,2,opt,name=featureUuid,proto3" json:"featureUuid,omitempty"`
	FeatureName   string                 `protobuf:"bytes,3,opt,name=featureName,proto3" json:"featureName,omitempty"`
	Mac           string                 `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`
	ApiToken      string                 `protobuf:"bytes,5,opt,name=api_token,json=apiToken,proto3" json:"api_token,omitempty"`
	Value         float32                `protobuf:"fixed32,6,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	mi := &file_api_grpc_device_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_device_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_device_device_proto_rawDescGZIP(), []int{2}
}

func (x *SetValueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetValueRequest) GetFeatureUuid() string {
	if x != nil {
		return x.FeatureUuid
	}
	return ""
}

func (x *SetValueRequest) GetFeatureName() string {
	if x != nil {
		return x.FeatureName
	}
	return ""
}

func (x *SetValueRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *SetValueRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

func (x *SetValueRequest) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FeatureUuid   string                 `protobuf:"bytes,3,opt,name=featureUuid,proto3" json:"featureUuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueResponse) Reset() {
	*x = SetValueResponse{}
	mi := &file_api_grpc_device_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResponse) ProtoMessage() {}

func (x *SetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_device_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResponse.ProtoReflect.Descriptor instead.
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_device_device_proto_rawDescGZIP(), []int{3}
}

func (x *SetValueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SetValueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetValueResponse) GetFeatureUuid() string {
	if x != nil {
		return x.FeatureUuid
	}
	return ""
}

var File_api_grpc_device_device_proto protoreflect.FileDescriptor

const file_api_grpc_device_device_proto_rawDesc = "" +
	"\n" +
	"\x1capi/grpc/device/device.proto\x12\x06device\"\x94\x01\n" +
	"\x0fGetValueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vfeatureUuid\x18\x02 \x01(\tR\vfeatureUuid\x12 \n" +
	"\vfeatureName\x18\x03 \x01(\tR\vfeatureName\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\tR\x03mac\x12\x1b\n" +
	"\tapi_token\x18\x05 \x01(\tR\bapiToken\"\xc0\x01\n" +
	"\x10GetValueResponse\x12 \n" +
	"\vfeatureUuid\x18\x01 \x01(\tR\vfeatureUuid\x12 \n" +
	"\vfeatureName\x18\x02 \x01(\tR\vfeatureName\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x02R\x05value\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vmodified_at\x18\x06 \x01(\x03R\n" +
	"modifiedAt\"\xaa\x01\n" +
	"\x0fSetValueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vfeatureUuid\x18\x02 \x01(\tR\vfeatureUuid\x12 \n" +
	"\vfeatureName\x18\x03 \x01(\tR\vfeatureName\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\tR\x03mac\x12\x1b\n" +
	"\tapi_token\x18\x05 \x01(\tR\bapiToken\x12\x14\n" +
	"\x05value\x18\x06 \x01(\x02R\x05value\"f\n" +
	"\x10SetValueResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vfeatureUuid\x18\x03 \x01(\tR\vfeatureUuid2\x8a\x01\n" +
	"\x06Device\x12?\n" +
	"\bGetValue\x12\x17.device.GetValueRequest\x1a\x18.device.GetValueResponse\"\x00\x12?\n" +
	"\bSetValue\x12\x17.device.SetValueRequest\x1a\x18.device.SetValueResponse\"\x00B0Z.github.com/Ks89/home-anthill/api-server/deviceb\x06proto3"

var (
	file_api_grpc_device_device_proto_rawDescOnce sync.Once
	file_api_grpc_device_device_proto_rawDescData []byte
)

func file_api_grpc_device_device_proto_rawDescGZIP() []byte {
	file_api_grpc_device_device_proto_rawDescOnce.Do(func() {
		file_api_grpc_device_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_device_device_proto_rawDesc), len(file_api_grpc_device_device_proto_rawDesc)))
	})
	return file_api_grpc_device_device_proto_rawDescData
}

var file_api_grpc_device_device_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_grpc_device_device_proto_goTypes = []any{
	(*GetValueRequest)(nil),  // 0: device.GetValueRequest
	(*GetValueResponse)(nil), // 1: device.GetValueResponse
	(*SetValueRequest)(nil),  // 2: device.SetValueRequest
	(*SetValueResponse)(nil), // 3: device.SetValueResponse
}
var file_api_grpc_device_device_proto_depIdxs = []int32{
	0, // 0: device.Device.GetValue:input_type -> device.GetValueRequest
	2, // 1: device.Device.SetValue:input_type -> device.SetValueRequest
	1, // 2: device.Device.GetValue:output_type -> device.GetValueResponse
	3, // 3: device.Device.SetValue:output_type -> device.SetValueResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_device_device_proto_init() }
func file_api_grpc_device_device_proto_init() {
	if File_api_grpc_device_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_device_device_proto_rawDesc), len(file_api_grpc_device_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_device_device_proto_goTypes,
		DependencyIndexes: file_api_grpc_device_device_proto_depIdxs,
		MessageInfos:      file_api_grpc_device_device_proto_msgTypes,
	}.Build()
	File_api_grpc_device_device_proto = out.File
	file_api_grpc_device_device_proto_goTypes = nil
	file_api_grpc_device_device_proto_depIdxs = nil
}
