package utils

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"os"
	"regexp"
)

// PKCEChallengeMethodS256 is the only PKCE challenge method accepted by GitHub
// and by this API. The plain method is intentionally not supported.
const PKCEChallengeMethodS256 = "S256"

var pkceVerifierPattern = regexp.MustCompile(`^[A-Za-z0-9._~-]{43,128}$`)
var pkceCodeChallengePattern = regexp.MustCompile(`^[A-Za-z0-9_-]{43,128}$`)
var appLoginCodePattern = regexp.MustCompile(`^[A-Za-z0-9_-]{128}$`)

// IsValidPKCEVerifier reports whether verifier matches the RFC 7636 verifier
// character set and length requirements.
func IsValidPKCEVerifier(verifier string) bool {
	return pkceVerifierPattern.MatchString(verifier)
}

// IsValidPKCECodeChallenge reports whether challenge is a valid base64url PKCE
// code challenge length and character set.
func IsValidPKCECodeChallenge(challenge string) bool {
	return pkceCodeChallengePattern.MatchString(challenge)
}

// IsValidAppLoginCode reports whether code matches the opaque mobile app login
// code format generated by RandomString(96).
func IsValidAppLoginCode(code string) bool {
	return appLoginCodePattern.MatchString(code)
}

// NewPKCEVerifier creates a high-entropy PKCE code verifier suitable for S256.
// The returned verifier uses the RFC 7636 maximum length of 128 characters.
func NewPKCEVerifier() (string, error) {
	return RandomString(96)
}

// BuildPKCECodeChallenge derives the S256 PKCE code challenge from a verifier.
// The verifier is validated before hashing so invalid values are rejected before
// they are stored in session or sent through the OAuth flow.
func BuildPKCECodeChallenge(verifier string) (string, error) {
	if !IsValidPKCEVerifier(verifier) {
		return "", fmt.Errorf("invalid PKCE code verifier")
	}

	sum := sha256.Sum256([]byte(verifier))
	return base64.RawURLEncoding.EncodeToString(sum[:]), nil
}

// HashToken returns a stable HMAC-SHA-256 base64url hash for opaque tokens that
// must be looked up server-side without storing the raw secret. The HMAC key
// acts as a server-side pepper, so a database leak alone is not enough to verify
// guessed tokens offline.
func HashToken(token string) string {
	mac := hmac.New(sha256.New, []byte(refreshTokenHashSecret()))
	_, _ = mac.Write([]byte(token))
	return base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
}

func refreshTokenHashSecret() string {
	if secret := os.Getenv("REFRESH_TOKEN_HASH_SECRET"); secret != "" {
		return secret
	}
	if secret := os.Getenv("JWT_REFRESH_PASSWORD"); secret != "" {
		return secret
	}
	return os.Getenv("JWT_PASSWORD")
}

// TruncateString returns input capped at maxLen bytes. Negative maxLen disables
// truncation.
func TruncateString(input string, maxLen int) string {
	if maxLen < 0 || len(input) <= maxLen {
		return input
	}
	return input[:maxLen]
}
