// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/grpc/register/register.proto

package register

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Uuid           string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Mac            string                 `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Manufacturer   string                 `protobuf:"bytes,5,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	Model          string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	ProfileOwnerId string                 `protobuf:"bytes,7,opt,name=profileOwnerId,proto3" json:"profileOwnerId,omitempty"`
	ApiToken       string                 `protobuf:"bytes,8,opt,name=apiToken,proto3" json:"apiToken,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_grpc_register_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_register_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_register_register_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RegisterRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetManufacturer() string {
	if x != nil {
		return x.Manufacturer
	}
	return ""
}

func (x *RegisterRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RegisterRequest) GetProfileOwnerId() string {
	if x != nil {
		return x.ProfileOwnerId
	}
	return ""
}

func (x *RegisterRequest) GetApiToken() string {
	if x != nil {
		return x.ApiToken
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	mi := &file_api_grpc_register_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_register_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_api_grpc_register_register_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_grpc_register_register_proto protoreflect.FileDescriptor

const file_api_grpc_register_register_proto_rawDesc = "" +
	"\n" +
	" api/grpc/register/register.proto\x12\bregister\"\xd9\x01\n" +
	"\x0fRegisterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03mac\x18\x03 \x01(\tR\x03mac\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\"\n" +
	"\fmanufacturer\x18\x05 \x01(\tR\fmanufacturer\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12&\n" +
	"\x0eprofileOwnerId\x18\a \x01(\tR\x0eprofileOwnerId\x12\x1a\n" +
	"\bapiToken\x18\b \x01(\tR\bapiToken\"A\n" +
	"\rRegisterReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2P\n" +
	"\fRegistration\x12@\n" +
	"\bRegister\x12\x19.register.RegisterRequest\x1a\x17.register.RegisterReply\"\x00B2Z0github.com/Ks89/home-anthill/api-server/registerb\x06proto3"

var (
	file_api_grpc_register_register_proto_rawDescOnce sync.Once
	file_api_grpc_register_register_proto_rawDescData []byte
)

func file_api_grpc_register_register_proto_rawDescGZIP() []byte {
	file_api_grpc_register_register_proto_rawDescOnce.Do(func() {
		file_api_grpc_register_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_grpc_register_register_proto_rawDesc), len(file_api_grpc_register_register_proto_rawDesc)))
	})
	return file_api_grpc_register_register_proto_rawDescData
}

var file_api_grpc_register_register_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_grpc_register_register_proto_goTypes = []any{
	(*RegisterRequest)(nil), // 0: register.RegisterRequest
	(*RegisterReply)(nil),   // 1: register.RegisterReply
}
var file_api_grpc_register_register_proto_depIdxs = []int32{
	0, // 0: register.Registration.Register:input_type -> register.RegisterRequest
	1, // 1: register.Registration.Register:output_type -> register.RegisterReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_register_register_proto_init() }
func file_api_grpc_register_register_proto_init() {
	if File_api_grpc_register_register_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_grpc_register_register_proto_rawDesc), len(file_api_grpc_register_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_register_register_proto_goTypes,
		DependencyIndexes: file_api_grpc_register_register_proto_depIdxs,
		MessageInfos:      file_api_grpc_register_register_proto_msgTypes,
	}.Build()
	File_api_grpc_register_register_proto = out.File
	file_api_grpc_register_register_proto_goTypes = nil
	file_api_grpc_register_register_proto_depIdxs = nil
}
