---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-config
  namespace: {{ .Values.namespace }}
data:
  .env: |-
    MONGO_URI={{ .Values.mongodbUrl }}
    MONGO_DB_NAME=sensors
    AMQP_URI=amqp://rabbitmq-svc.{{ .Values.namespace }}.svc.cluster.local:5672
    AMQP_QUEUE_NAME=ks89
    AMQP_CONSUMER_TAG=consumer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-consumer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-consumer
  template:
    metadata:
      labels:
        app: ac-consumer
    spec:
      containers:
      - name: ac-consumer
        image: {{ .Values.consumer.image }}
        {{- if .Values.debug.pods.alwaysPullContainers }}
        imagePullPolicy: Always
        {{- end }}
        {{- if .Values.debug.pods.sleepInfinity }}
        command: ["/bin/sh"]
        args: ["-c", "chmod +x /app/consumer; /app/consumer; sleep Infinity;"]
        {{- end }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: consumer-config
          mountPath: /app/.env
          subPath: .env
          readOnly: true
      volumes:
      - name: consumer-config
        configMap:
          name: consumer-config
---
kind: Service
apiVersion: v1
metadata:
  name: consumer-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ac-consumer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http