---
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: {{ .Values.namespace }}
data:
  .env: |-
    AMQP_URI=amqp://rabbitmq-svc.{{ .Values.namespace }}.svc.cluster.local:5672
    AMQP_QUEUE_NAME=ks89
    {{- if .Values.mosquitto.ssl.enable }}
    MQTT_URL={{ .Values.domains.mqtt }}
    MQTT_PORT=8883
    MQTT_TLS=true
    ROOT_CA=/etc/ssl/certs/ISRG_Root_X1.pem
    # ca.pem = ISRG_Root_X1.pem + cert.pem
    MQTT_CERT_FILE=/etc/letsencrypt/live/{{ .Values.domains.mqtt }}/cert.pem
    MQTT_KEY_FILE=/etc/letsencrypt/live/{{ .Values.domains.mqtt }}/privkey.pem
    {{ else }}
    MQTT_URL=mosquitto-svc.{{ .Values.namespace }}.svc.cluster.local
    MQTT_PORT=1883
    MQTT_TLS=false
    ROOT_CA=
    MQTT_CERT_FILE=
    MQTT_KEY_FILE=
    {{ end -}}
    MQTT_CLIENT_ID=producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-producer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-producer
  template:
    metadata:
      labels:
        app: ac-producer
    spec:
      containers:
      - name: ac-producer
        image: {{ .Values.producer.image }}
        {{- if .Values.debug.pods.alwaysPullContainers }}
        imagePullPolicy: Always
        {{- end }}
        {{- if .Values.debug.pods.sleepInfinity }}
        command: ["/bin/sh"]
        args: ["-c", "chmod +x /app/producer; /app/producer; sleep Infinity;"]
        {{- end }}
        ports:
        - name: amqp
          containerPort: 5672
          protocol: TCP
        {{- if .Values.mosquitto.ssl.enable }}
        - name: mqtts
          containerPort: 8883
          protocol: TCP
        {{- else }}
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        {{- end }}
        volumeMounts:
        - name: producer-config
          mountPath: /app/.env
          subPath: .env
          readOnly: true
        {{ if .Values.mosquitto.ssl.enable }}
        - name: lets-encrypt-ssl-mqtt-storage
          mountPath: "/etc/letsencrypt/"
        {{ end }}
      volumes:
      - name: producer-config
        configMap:
          name: producer-config
      {{ if .Values.mosquitto.ssl.enable }}
      - name: lets-encrypt-ssl-mqtt-storage
        persistentVolumeClaim:
          claimName: lets-encrypt-ssl-mqtt-claim
      {{ end }}
---
kind: Service
apiVersion: v1
metadata:
  name: producer-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ac-producer
  ports:
    {{- if .Values.mosquitto.ssl.enable }}
    # expose mqtts port
    - name: mqtts
      protocol: TCP
      port: 8883
      targetPort: mqtts
    {{- else }}
    # expose mqtt port
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: mqtt
    {{- end }}
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
