apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image }}
        ports:
        - name: amqp
          containerPort: 5672
          protocol: TCP
        # - name: mgmt
        #   containerPort: 15672
        #   protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
    # - name: mgmt
    #   protocol: TCP
    #   port: 15672
    #   targetPort: mgmt