---
apiVersion: v1
kind: ConfigMap
metadata:
  name: register-config
  namespace: {{ .Values.namespace }}
data:
  .env: |-
    MONGO_URI={{ .Values.mongodbUrl }}
    MONGO_DB_NAME=sensors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac-register
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ac-register
  template:
    metadata:
      labels:
        app: ac-register
    spec:
      containers:
      - name: ac-register
        image: {{ .Values.register.image }}
        env:
        - name: ENV
          value: "prod"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: rabbitmqgui
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: register-config
          mountPath: /.env
          subPath: .env
          readOnly: true
      volumes:
      - name: register-config
        configMap:
          name: register-config
---
kind: Service
apiVersion: v1
metadata:
  name: register-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ac-register
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: rabbitmqgui
      protocol: TCP
      port: 8080
      targetPort: http